from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field, create_model


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list)
    user_question: str = Field(..., description="The original question asked by the user")
    source_id: str = Field(..., description="Saved source the question is about")
    sql_dialect: str = Field(default="postgres", description="SQL dialect of the source: postgres or duckdb")
    schema_context: str = Field(default="", description="Rendered schema sent to the model")
    selected_tables: list[str] = Field(default_factory=list, description="Tables whose detail was sent")
    notes_used: list[str] = Field(default_factory=list, description="User note paths included in the prompt")
    generated_sql_query: str = Field(default="", description="SQL generated by the agent")
    sql_attempts: int = Field(default=0, description="Generations so far, counting the first")
    sql_errors: Annotated[list[dict], add] = Field(
        default_factory=list, description="One {attempt, code, detail, sql} per failed attempt"
    )
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Did the SQL pass the read-only check")
    comments: str = Field(default="", description="Why the read-only check refused the SQL")
    result_columns: list[str] = Field(default_factory=list, description="Columns of the executed query")
    result_rows: list[list] = Field(default_factory=list, description="Rows, capped at MAX_FETCH_ROWS")
    result_row_count: int = Field(default=0, description="Number of rows returned")
    result_truncated: bool = Field(default=False, description="True if more rows existed than were fetched")
    final_answer: str = Field(default="", description="Answer returned to the user")
    error_code: str = Field(default="", description="Machine-readable failure code, empty on success")
    error_detail: str = Field(default="", description="Human-readable failure detail")
    row_limit: int = Field(default=25, description="LIMIT added when the SQL has none; charts raise it")
    chart_spec: dict | None = Field(default=None, description="Vega-Lite spec, when a chart was drawn")
    chart_error: str = Field(default="", description="chart.* code when no chart could be drawn")
    chart_error_detail: str = Field(default="", description="Why no chart was drawn")
    chart_note: str = Field(default="", description="Caveat shown with the chart, e.g. rows were cut off")


class ETLAgentSchema(BaseModel):
    user_request: str = Field(..., description="What the user asked to extract or transform")
    source_id: str = Field(..., description="Saved source a transform reads from")
    sql_dialect: str = Field(default="postgres", description="SQL dialect of the source: postgres or duckdb")
    schema_context: str = Field(default="", description="Rendered tables of the source")
    plan: dict = Field(default_factory=dict, description="The model's plan: kind, url or sql, name, format")
    attempts: int = Field(default=0, description="Plans made so far, counting the first")
    errors: Annotated[list[dict], add] = Field(
        default_factory=list, description="One {attempt, code, detail} per failed attempt"
    )
    output: dict = Field(default_factory=dict, description="Saved file: path, rows, columns, table")
    final_answer: str = Field(default="", description="Answer returned to the user")
    error_code: str = Field(default="", description="Machine-readable failure code, empty on success")
    error_detail: str = Field(default="", description="Human-readable failure detail")


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list)
    source_id: str = Field(..., description="Saved source the question is about")
    route_response: str = Field(default="", description="Which sub-agent the router picked")
    route_confidence: float = Field(default=0.0, description="Router confidence, 0 to 1")
    route_source: str = Field(default="", description="Who decided: jev, llm or human")
    clarify_question: str = Field(default="", description="What to ask the user when the route is unclear")
    clarify_why: str = Field(default="", description="Why the route is unclear")
    clarify_explanation: str = Field(default="", description="Plain explanation shown when the user asked for help")
    clarify_rounds: int = Field(default=0, description="Times the user asked for help instead of choosing")
    chart_spec: dict | None = Field(default=None, description="Vega-Lite spec from the chart agent")
    chart_error: str = Field(default="", description="chart.* code when no chart could be drawn")
    chart_note: str = Field(default="", description="Caveat shown with the chart")


def build_router_schema(keys: tuple[str, ...]) -> type[BaseModel]:
    """Structured-output schema: one of the agent keys, or "unclear" with a question for the user."""
    return create_model(
        "RouterSchema",
        answer=(Literal[(*keys, "unclear")], Field(..., description="Which agent should handle this, or unclear")),
        question=(str, Field(default="", description="If unclear: one short question that would settle it")),
        why=(str, Field(default="", description="If unclear: what makes it unclear, in one sentence")),
    )
