from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field, create_model


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list)
    user_question: str = Field(..., description="The original question asked by the user")
    curated_ques: str = Field(default="", description="Curated user question")
    prompt_query_context: str = Field(default="", description="Prompt with DB schema context")
    generated_sql_query: str = Field(default="", description="SQL generated by the agent")
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Is the SQL safe to execute")
    comments: str = Field(default="", description="Judge's reasoning about SQL safety")
    sql_query_execution_result: str = Field(default="", description="Result of running the SQL")
    final_answer: str = Field(default="", description="Answer returned to the user")
    error_code: str = Field(default="", description="Machine-readable failure code, empty on success")
    error_detail: str = Field(default="", description="Human-readable failure detail")


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Is the SQL query safe to execute")
    comments: str = Field(..., description="Reasoning behind the decision")


class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list)
    tool_failures: int = Field(default=0, description="Count of failed tool calls, used to stop retry loops")


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list)
    route_response: str = Field(default="", description="Which sub-agent the router picked")
    route_confidence: float = Field(default=0.0, description="Router confidence, 0 to 1")
    is_ambiguous: float = Field(default=0.0, description="Probability the request is too vague to act on")


def build_router_schema(keys: tuple[str, ...]) -> type[BaseModel]:
    """Structured-output schema constrained to the registered agent keys."""
    return create_model(
        "RouterSchema",
        answer=(Literal[keys], Field(..., description="Which agent should handle this request")),
        comments=(str, Field(default="", description="Why this route was chosen")),
    )
